### ISSUE TITLE
Stopping/Closing the app resets the playlist including current song

### ISSUE THREAD

**Issue by phibo23** [TVLukeProductions/TrashPlay#13]
This is a violation of the first and the second rule of the trash playlist.

**Comment by TVLuke** [comment]
WHAT? NO! WHAT? What version are you using?

**Comment by TVLuke** [comment]
Because this shit should have been fixed since like... two days ago.

**Comment by phibo23** [comment]
1.0.9, updated this morning.

**Comment by TVLuke** [comment]
What the... I am using trashplay for hours on two devices here, this is not reproducible. Believe me, I wish it was. #GrönemeierKannNichtTanzen

**Comment by TVLuke** [comment]
Anyway. 1.0.10 will reset your entire database, maybe thats fixes the issue (but I don't get it)
