### ISSUE TITLE
service icon semantics

### ISSUE THREAD

**Issue by phibo23** [TVLukeProductions/TrashPlay#9]
Coloured icons mean deactivated and grey icons mean activated (e.g. dropbox connected). WAT?! That is totally counterintuitive... I guess you know that since you explain it in the read me file. Why did you make this decision in the first place (long time ago...)? O.o

**Comment by TVLuke** [comment]
I think (possibly) the idea was, if its coloured you need to do stuff if its greyed out you're done. Not sure. I noticed this during the rewrite but kept it since it had not come up as an issue before...

**Comment by TVLuke** [comment]
Will be fixed in 1.0.5
